name: Build apk for production

on: [push, pull_request]
  - branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use NodeJS v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Create env file
        run: |
          touch .env
          echo PAYMONGO_SECRET_KEY=${{ secrets.PAYMONGO_SECRET_KEY_LIVE }} >> .env
          echo API_KEY=${{ secrets.API_BASE_URL_PROD }} >> .env
          echo GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID_PROD }} >> .env
          cat .env

      - name: build release 
        run: ./gradlew assembleRelease
        run: npm ci
        run: npm run prod
        run: npm run generate:services:prod
        run: ./gradlew assembleRelease -Dorg.gradle.logging.level=info
        working-directory: android
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: '**/*.apk'
