name: Build apk for production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use NodeJS v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_release_keys.sh
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}


      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Create env file
        run: |
          touch .env
          echo PAYMONGO_SECRET_KEY=${{ secrets.PAYMONGO_SECRET_KEY_LIVE }} >> .env
          echo API_KEY=${{ secrets.API_BASE_URL_PROD }} >> .env
          echo GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID_PROD }} >> .env
          echo GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }} >> .env
          echo FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} >> .env
          cat .env

      - name: Run yarn clean install
        run: IGNORE_SCRIPTS=1 yarn --frozen-lockfile

      - name: Generate services
        run: yarn run generate:services:prod

      - name: Fix images
        run: npx react-native-fix-image

      - name: Run gradle clean
        working-directory: android
        run: ./gradlew clean --no-daemon

      - run: mkdir -p ./android/app/src/staging/assets
      - name: Compile android bundle
        run: APP_ENV=production npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/release/assets/index.android.bundle --assets-dest android/app/src/release/res/

      - name: Build android apk
        run: APP_ENV=production ./gradlew :app:assembleRelease --no-daemon
        working-directory: android

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: '**/*.apk'
